databases:
  - name: dblivelyteams
    databaseName: dblivelyteams
    user: dblivelyteams

services:
  - type: web
    name: livelyteams
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dbspreaddirt
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
