menubar: false

toolbar:
  - undo redo | styleselect | bold italic underline | fontselect | fontsizeselect | bullist numlist | outdent indent | alignleft aligncenter alignright | link

plugins:
  - link lists code
